/**
 * Text constant.
 * @file 文案常量
 * @description 用于全局路由请求的响应文案
 */

export const HTTP_ERROR_SUFFIX = '失败';
export const HTTP_SUCCESS_SUFFIX = '成功';
export const HTTP_DEFAULT_TEXT = '数据请求';
export const HTTP_DEFAULT_ERROR_TEXT = HTTP_DEFAULT_TEXT + HTTP_ERROR_SUFFIX;
export const HTTP_DEFAULT_SUCCESS_TEXT = HTTP_DEFAULT_TEXT + HTTP_SUCCESS_SUFFIX;

export const VALIDATION_ERROR_DEFAULT = 'FAIL_VALIDATIE';
export const UNAUTHORIZED_ERROR_DEFAULT = 'UNAUTHENTICATED';
export const INTERNAL_ERROR_DEFAULT = 'INTERNAL_ERROR';
export const NOTFOUND_ERROR_DEFAULT = 'NOT_FOUND';
export const CONFLICT_ERROR_DEFAULT = 'CONFLICT';
